version: "3.9"

services:
  dbt:
    container_name: dbt
    build: .
    volumes:
      # - ./dbt_project/dbt_project.yml:/usr/src/dbt_project/dbt_project.yml
      - ./dbt_project/profiles.yml:/root/.dbt/profiles.yml
      - ./dbt_project/:/usr/src/dbt_project/
    # command: /bin/sh -c "dbt deps && dbt run"
    command: /bin/sh -c "sleep infinity"
    networks:
      - my_network







networks:
  my_network:
    driver: bridge
    external: true