version: '3'

services:
  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    ports:
      - "8888:8888"
    volumes:
      - ./conf.dist:/usr/share/hue/desktop/conf
    networks:
      - my_network



networks:
  my_network:
    driver: bridge
    external: true
  